version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fridgerator

  fridgerator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/code
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - fridgerator

networks:
  fridgerator:
    driver: bridge

volumes:
  dbdata:
    driver: local
