# Generated by Django 5.0.6 on 2024-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="id",
        ),
        migrations.AddField(
            model_name="setting",
            name="setting_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
