# Generated by Django 5.0.6 on 2024-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_setting_id_setting_setting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
